import type { Metadata } from 'next';

import Wrapper from '.';
import { inter } from '../../fonts';
import './globals.scss';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <Wrapper>{children}</Wrapper>
      </body>
    </html>
  );
}
